image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    new-releases:
      - step:
          name: Confluence Alpine
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='false'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE='Dockerfile-alpine'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='alpine,alpine-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
      - step:
          name: Confluence Ubuntu
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='adoptopenjdk8,jdk8,ubuntu,ubuntu-18.04-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
    ubuntu-custom-release:
      - variables:
          - name: CONFLUENCE_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/confluence-server:${DOCKER_TAG}
              --build-arg CONFLUENCE_VERSION=${CONFLUENCE_VERSION} .
            - docker push atlassian/confluence-server:${DOCKER_TAG}
    alpine-custom-release:
      - variables:
          - name: CONFLUENCE_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - >
              docker build -t atlassian/confluence-server:${DOCKER_TAG} 
              -f Dockerfile-alpine
              --build-arg CONFLUENCE_VERSION=${CONFLUENCE_VERSION} .
            - docker push atlassian/confluence-server:${DOCKER_TAG}
  branches:
    master:
      - step:
          name: Confluence Alpine
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='false'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE='Dockerfile-alpine'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='alpine,alpine-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update
      - step:
          name: Confluence Ubuntu
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='adoptopenjdk8,jdk8,ubuntu,ubuntu-18.04-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update
  pull-requests:
    '**':
      - step:
          image: python:3.7-alpine3.9
          services:
            - docker
          script:
            - pip install -q -r tests/test-requirements.txt
            - py.test tests/
definitions:
  services:
    docker:
      memory: 2048